#!/bin/bash

head -23 ../usr/share/doc/config > /etc/default/lxc-net

tail -5 ../usr/share/doc/config >> /etc/network/interfaces

echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/ipv4forward

echo "Installation réussie !"
