#!/bin/bash

cp ../usr/share/doc/lxc-net /etc/default/lxc-net) && echo "Le fichier lxc-net a bien été créer" && systemctl restart lxc-net && ip tuntap add mode tap tap0 && ip link set dev tap0 master vswitch0 && ip link set tap0 up && echo "Installation réussie !"